-- 创建数据库

CREATE DATABASE IF NOT EXISTS msg CHARACTER SET UTF8 COLLATE utf8_general_ci;

USE msg;

-- 留言
CREATE TABLE IF NOT EXISTS `msg`
(
    `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` CHAR(20) NOT NULL COMMENT '作者姓名',
    `email` CHAR(60) NOT NULL COMMENT '邮箱',
    `text` TEXT NOT NULL COMMENT '内容', 
    `time` DATETIME NOT NULL COMMENT '发表时间',
    PRIMARY KEY(id)
) ENGINE=MyISAM AUTO_INCREMENT=101;